### ISSUE TITLE
Decision on new or existing format

### ISSUE THREAD

**Issue by sneumann** [HUPO-PSI/SpectralLibraryFormat#10]
Based on the outcomes of #4, #5, #7, #9, it should be checked 
if/which any of the existing https://github.com/HUPO-PSI/SpectralLibraryFormat/tree/master/legacy-formats
can already encode the required information, or how much (little) 
would be required to extend an existing format. Plus, one of the areas where PSI excels 
is to create controlled vocabularies, harmonise adoption and provide validators, 
so libraries and software can claim they are supporting the PSI SpectralLibraryFormat.

**Comment by ypriverol** [comment]
@sneumannwe have discussed on PSI about this issue of the extension. Some of the points that trigger the decision on creating a new format extension: 

- It will be confusing for the end user to know if the file format is the one developed by PSI or the proprietary one. 
- @jshofstahl mentioned for example that **msp** is a proprietary format and also a windows extension.
- We don't have the right to change the file format of somebody else. 
- We agree to align as much as possible the current file formats to the new file enabling readers/writers to easily transform current legacy representations to the file format. For that reason, we discuss that we need to focus now the discussion around which metadata is mandatory/optional at spectrum and library levels.

**Comment by meowcat** [comment]
Note, in the google docs I added a link to some investigations into the MSP format I once did. The NIST library converter does in fact allow roundtripping of some undocumented entries.

If anything like MSP should be chosen as a base format, the most fruitful idea IMO would be to try to get NIST / S. Stein onboard. In that case
* there is no issue of changing "someone else's" file format
* if NIST themselves adopt "our" changes, the format will be immediately widely distributed.

**Comment by ypriverol** [comment]
@meowcat I fully agree with you. @edeutsch can we contact the NIST people to be involved in this development. If they agree we can keep the **msp** name. However, if they are not involved, it will be difficult to maintain the name because then it will be two representations for the same file type. The current document is trying to capture the metadata at the library level: 

https://docs.google.com/document/d/1LgSGtR_t5IcUS9rV7YtsLveDVX9X8KsOpU-5NJ4vuYI/edit?usp=sharing

**Comment by edeutsch** [comment]
Yes, we can and should and will. We should also get Paul Rudnick involved if he still so wishes.

**Comment by meowcat** [comment]
Another thought that has crossed my mind would be that it would be nice to have a format that has a very simple canonical transformation to YAML. Both the MassBank and msp formats are actually not that far from it.

**Comment by RalfG** [comment]
Since, we settled on multiple representations of the format, using the same controlled vocabulary and principles, this issue can be closed.
