### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by meowcat** [HUPO-PSI/SpectralLibraryFormat#11]
Hi,

I just wanted to follow up on this - is this going anywhere?

**Comment by RalfG** [comment]
I think the last thing that was done, was the article, which listed the minimal requirements for a spectral library format. I remember from the PSI meeting last year that there still was some discussion on which file format would be best (eg HDF, XML-based...). Personally, I'm a big fan of something HDF-like, as it can contain the multiple tables that were discussed before (the different levels of information: library, spectrum, peak...) and supports very fast access. 
I'm new to defining file formats, but I would be happy to help where I can!

**Comment by RalfG** [comment]
To give a quick update on this: the standardized spectral library format is in very active development at the PSI workgroup. We are now pretty much finished with defining the metadata into an updated PSI-MS controlled vocabulary, and the formatting of the different representations - text (msp-like), json and tabular (csv, tsv, hdf...) - is being discussed.
