### ISSUE TITLE
Definition of the attributes and terms for Spectral library.

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/SpectralLibraryFormat#4]
We are currently editing a document in google docs with the current terms in MSP and the corresponding proposals in the SpectralLibraryFormat. 

Document here: https://docs.google.com/document/d/1LgSGtR_t5IcUS9rV7YtsLveDVX9X8KsOpU-5NJ4vuYI/edit?usp=sharing

**Comment by edeutsch** [comment]
This seems to be the same issue as issue #7? Closing.
