### ISSUE TITLE
Confirmation of example 

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/SpectralLibraryFormat#6]
@sneumann @jshofstahl can you confirm that you have seen this type of annotation also: 

https://github.com/HUPO-PSI/SpectralLibraryFormat/blob/master/examples/legacy-formats/metabolomics/PB000447.txt

If not I will remove the example.

**Comment by jshofstahl** [comment]
Yes that file is an example of a MassBank file and I can read and import it in our application.

**Comment by sneumann** [comment]
For a bit more on MassBank in the contest of the SpectralLibraryFormat
see https://github.com/HUPO-PSI/SpectralLibraryFormat/blob/master/legacy-formats/MassBank.md
